import React from 'react';
import { ShieldCheck, Lock, Info } from 'lucide-react';

export const PrivacyTermsPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-white">Privacy Policy & Terms of Service</h1>
        <p className="text-xs text-slate-400">Data protection, sandbox disclaimers, and consent guidelines</p>
      </div>

      <div className="fintech-card p-8 space-y-6 text-xs text-slate-300 leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-base font-bold text-white flex items-center space-x-2">
            <Lock className="w-4 h-4 text-blue-400" />
            <span>1. Financial Data Consent Architecture</span>
          </h2>
          <p>
            LoanCompare AI operates on explicit, version-controlled user consent. Financial profile attributes are processed exclusively for estimating loan eligibility, calculating Debt-to-Income (DTI) ratios, evaluating risk with Gradient Boosting ML models, and matching published bank product criteria.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-white flex items-center space-x-2">
            <Info className="w-4 h-4 text-amber-400" />
            <span>2. Academic Demo & Sandbox Limitation</span>
          </h2>
          <p>
            LoanCompare AI is built as a final-year academic/college demonstration project. It does NOT claim or implement unauthorized access to government PAN databases, CIBIL, Experian, Equifax, or private banking APIs. Mock provider services (`MockPANVerificationService`, `MockCreditDataService`, `MockOTPService`) simulate external provider responses.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-white flex items-center space-x-2">
            <ShieldCheck className="w-4 h-4 text-purple-400" />
            <span>3. No Guarantee of Credit Approval</span>
          </h2>
          <p>
            Eligibility results generated by LoanCompare AI are indicative model assessments and do not constitute loan approval or a binding credit guarantee. Final credit underwriting, interest rate determination, and loan disbursement remain exclusively with authorized third-party lenders.
          </p>
        </section>
      </div>
    </div>
  );
};
